spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:tsriWsICIuXHDqOjgRupbOgRvyWKFKVc}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    show-sql: true

jwt:
  secret: ${JWT_SECRET:petCareSecretKeyForJWTTokenGenerationMustBeLongEnoughForHS256Algorithm}
  expiration: ${JWT_EXPIRATION:86400000}
